name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  RUST_BACKTRACE: 1

jobs:
  windows:
    name: Build on Windows
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      # msys2 required by rug
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            pacman-mirrors
            diffutils
            m4
            make
            openssl
            openssl-devel
          pacboy: >-
            gcc:p
            rust:p

      - shell: msys2 {0}
        run: |
          cargo build

  mac:
    name: Build on MacOs
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@nextest

      - name: Build
        run: cargo build
