name: Publish

on:
  push:
    tags:
    - "*"
  workflow_dispatch:


env:
  IMAGE_NAME: skyf0l/rsacracker

jobs:
  crates_io:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout sources
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Install stable toolchain
      uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        toolchain: stable
        override: true

    - run: cargo publish --token ${CRATES_TOKEN}
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  docker_hub:
    name: Publish to hub.docker.com
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Install yq
      run: |
        sudo wget https://github.com/mikefarah/yq/releases/download/${VERSION}/${BINARY} -O /usr/bin/yq
        sudo chmod +x /usr/bin/yq
      env:
        VERSION: v4.40.5
        BINARY: yq_linux_amd64

    - name: Get package version
      id: get_version
      run: echo VERSION=$(yq ".package.version" Cargo.toml) >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@31159d49c0d4756269a0940a750801a1ea5d7003 # v6.1.0
      with:
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }},${{ env.IMAGE_NAME }}:latest
